name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    container:
      image: rust:alpine
    steps:
      - name: Checkout main branch
        uses: actions/checkout@main
      - name: Setup Dependencies
        run: |
          rustup update
          rustup component add clippy rustfmt
      - name: Checking Formatting
        run: |
          cargo fmt --all -- --check
      - name: Linting
        run: |
          cargo clippy --all-targets --all-features
